-- V1: Core schema
-- Flyway runs this only once. If the table already exists in a real DB,
-- this migration is skipped (checksum tracked in flyway_schema_history).

CREATE TABLE IF NOT EXISTS app_user (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)     NOT NULL UNIQUE,
    email       VARCHAR(100)    NOT NULL UNIQUE,
    password    VARCHAR(255)    NOT NULL,
    role        VARCHAR(20)     NOT NULL DEFAULT 'USER',
    enabled     BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)    NOT NULL,
    description TEXT,
    price       NUMERIC(12,2)   NOT NULL,
    stock       INT             NOT NULL DEFAULT 0,
    active      BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL REFERENCES app_user(id),
    status          VARCHAR(30)     NOT NULL DEFAULT 'PENDING',
    total_amount    NUMERIC(14,2)   NOT NULL DEFAULT 0,
    note            TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_item (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT          NOT NULL REFERENCES orders(id),
    product_id  BIGINT          NOT NULL REFERENCES product(id),
    quantity    INT             NOT NULL,
    unit_price  NUMERIC(12,2)   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id  ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status   ON orders(status);
CREATE INDEX IF NOT EXISTS idx_order_item_order ON order_item(order_id);
